version: '3'

services:
    backend:
        build: ./backend
        networks:
            - my-network

    sidecar:
        build: ./sidecar
        networks:
            - my-network

    ambassador:
        build: ./ambassador
        ports:
            - 80:80
        networks:
            - my-network

networks:
    my-network:
